name = "infopage"
license = "MIT"
licenselink = "https://github.com/colorchestra/hugo-infopage/blob/main/LICENSE.md"
description = "Create simple pages with some pages on it. Not a blog, not a personal website, just some information for you to slap wherever."
homepage = "https://github.com/colorchestra/hugo-infopage"
tags = ["singlepage", "minimal", "monospace", "dark mode", "responsive", "no-js", "no-tracking"]
features = ["singlepage", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "morph / colorchestra"
  homepage = "morph.sh"